nelmio_api_doc:
    documentation:
        info:
            title: Twitter telegram bot
            description: Here you can find information about usage API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/twitter # Accepts routes under /twitter
