version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports: 
      - '9000:9000'
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports: 
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: twitter_telegram_bot
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8888:8080'

volumes:
  mariadb: